### PR TITLE
Baraa

### PR DESCRIPTION
**Pull request by BaraaTal**
Classic Process Models has two models which are:
1-Linear Model
2-Iterative Model

### CODE REVIEW

**Review by rudyattieh — COMMENTED** [review]
you still have 5 empty files submitted without a folder name.
you are only modifying the descruption of the pr. this is not what is asked.

**Comment by BaraaTal** [comment]
Hello Dr
I have created a new folder with a new file and put a commit inside it.
This is a photo of what I did on GitBash.
Please if you find any mistake just let me know what is the wrong step in
order to modify my work and send it again.



‫في الخميس، 16 سبتمبر 2021 في 2:33 م تمت كتابة ما يلي بواسطة ‪Rudy Attieh‬‏
***@***.***‬‏>:‬

**Comment by BaraaTal** [comment]
Hello Dr
I send a pull request now.
Can you check it if it works?


‫في الخميس، 16 سبتمبر 2021 في 2:51 م تمت كتابة ما يلي بواسطة ‪Baraa Al
Tal‬‏ ***@***.***‬‏>:‬

**Comment by BaraaTal** [comment]
Hello Dr
I sent a pull request now
I think the file is filled now.
Please can you check it?


‫في الخميس، 16 سبتمبر 2021 في 3:32 م تمت كتابة ما يلي بواسطة ‪Baraa Al
Tal‬‏ ***@***.***‬‏>:‬

**Pull request closed without merging**
